default: &defaults
  ignore_user_agent_locale: false
  display_user_avatars: false
  default_user_avatar: 'mm'
  user_avatar_api_url: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
